#ifndef _GK_FACE3D
#define _GK_FACE3D

#include "Common.h"

namespace GK
{
	enum Face3D
	{
		Face3DFront = GL_TEXTURE_CUBE_MAP_NEGATIVE_Z,
		Face3DBack = GL_TEXTURE_CUBE_MAP_POSITIVE_Z,
		Face3DLeft = GL_TEXTURE_CUBE_MAP_NEGATIVE_X,
		Face3DRight = GL_TEXTURE_CUBE_MAP_POSITIVE_X,
		Face3DTop = GL_TEXTURE_CUBE_MAP_POSITIVE_Y,
		Face3DBottom = GL_TEXTURE_CUBE_MAP_NEGATIVE_Y
	};
}

#endif